- link:
    ~/.config/git/config: configs/git/gitconfig
    ~/.config/git/ignore: configs/git/gitignore
- shell:
    -
        description: "Create gitignore if connected to Internet"
        command: "./configs/git/mk-gitignore.sh"
        stdout: true
        stderr: true

#  vim: set filetype=yaml ts=4 sw=4 tw=0 et :
