- shell:
    -
        description: Load private Brewfile if present
        command: if [[ -f configs/homebrew/private-brewfile ]]; then brew bundle --file=configs/homebrew/private-brewfile; fi
        stdout: true
        stderr: true
- brewfile:
    file: configs/homebrew/brewfile

#  vim: set filetype=yaml ts=4 sw=4 tw=0 et :
