- shell:
    -
        description: Load private Brewfile if present
        command: if [[ -f configs/homebrew/private-brewfile ]]; then brew bundle --file=configs/homebrew/private-brewfile; fi
        stdout: true
        stderr: true
- shell:
    -
        description: Load Brewfile if present
        command: if [[ -f configs/homebrew/brewfile ]]; then brew bundle --file=configs/homebrew/brewfile; fi
        stdout: true
        stderr: true
# TODO (Chris): Get brewfile plugin to not throw error if default Brewfile doesn't exist.
#- brewfile:
#    file: configs/homebrew/brewfile
#    stdout: true
#    stderr: true

#  vim: set filetype=yaml ts=4 sw=4 tw=0 et :
