- shell:
    -
        description: Load private Brewfile if present
        command: [[ -f configs/homebrew/private-brewfile ]] && brew bundle --file=configs/homebrew/private-brewfile
        stdout: true
- brew:
    file: configs/homebrew/brewfile

#  vim: set filetype=yaml ts=4 sw=4 tw=0 et :
