#!/usr/bin/env bash

set -e

BASE_CONFIG="base"
CONFIG_SUFFIX=".yaml"

META_DIR="meta"
CONFIG_DIR="configs"
PROFILES_DIR="profiles"
PLUGINS_DIR="plugins"

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

pushd "${BASE_DIR}" &>> /dev/null

profile="${META_DIR}/${PROFILES_DIR}/$1"

if [[ ! -f ${profile} ]]; then
    echo "FATAL: Could not find profile (${profile})."
    popd &>> /dev/null
    exit 1
fi

while IFS= read -r config; do
    CONFIGS+=" ${config}"
done < "${profile}"

shift

for dir in $(find "${META_DIR}/${PLUGINS_DIR}" \
    -type d -name "dotbot-*"); do
    plugins+="--plugin-dir ${dir} "
done

for config in ${CONFIGS} ${@}; do
    echo -e "\nConfigure $config"
    configContent="$(<"${BASE_DIR}/${META_DIR}/${BASE_CONFIG}${CONFIG_SUFFIX}")\n$(<"${BASE_DIR}/${META_DIR}/${CONFIG_DIR}/${config}${CONFIG_SUFFIX}")"
    "${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" ${plugins} -c <(echo -e "$configContent")
done

popd &>> /dev/null