- defaults:
    link:
        create: true
        relink: true

- shell:
    - ["git submodule update --init --recursive", "Installing submodules"]

- clean: [
    '~',
    '~/.config'
]
#  vim: set filetype=yaml ts=4 sw=4 tw=0 et :
