#!/usr/bin/env zsh

export fpath=("${XDG_CONFIG_HOME:-${HOME}/.config}/zsh/functions" ${fpath})

autoload -Uz get_my_os
autoload -Uz is_bsd_based is_macos
autoload -Uz is_linux_based is_redhat_based is_debian_based
autoload -Uz is_windows_based
autoload -Uz substitute_command