#!/usr/bin/env zsh

# oh-my-zsh options
export ZSH="${HOME}/.config/zsh/oh-my-zsh"
export ZSH_CUSTOM="${ZDOTDIR}/omz-customizations"
DEFAULT_USERS=(waltripc cawaltrip)
ZSH_THEME="chriswaltrip"
CASE_SENSITIVE="true" # Case-sensitive completion
# HYPHEN_INSENSITIVE="true" # Hyphen-insensitive - Case-sensitive must be off.
# DISABLE_AUTO_UPDATE="true"
DISABLE_UPDATE_PROMPT="true" # Update without prompting
# export UPDATE_ZSH_DAYS=13 # Interval to check for updates
# DISABLE_MAGIC_FUNCTIONS="true" # Fix pasting URLS/other text.
# DISABLE_AUTO_TITLE="true" 
COMPLETION_WAITING_DOTS="true" # Add red dots whilst waiting for completion.
#DISABLE_UNTRACKED_FILES_DIRTY="true" # Speed up prompt @ large VCS repos
# ZSH_CUSTOM=/path/to/new-custom-folder # Custom zsh plugins directory
VSCODE=code
ZSH_DISABLE_COMPFIX="true"

# oh-my-zsh plugins
plugins=(git gitfast aws battery brew colored-man-pages colorize)
plugins+=(command-not-found)
plugins+=(emoji iterm2 osx tmux vscode)

# Start oh-my-zsh
source "${ZSH}/oh-my-zsh.sh"