#!/usr/bin/env zsh

# TODO (Chris): Move git-extras checks to its own file.
# TODO (Chris): Speed up searching for git-extras autocompletion for other OSes.

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export LANG=en_US.UTF-8

# Read in other configuration files
source ${ZDOTDIR:-~/.config/zsh}/zsh_options
source ${ZDOTDIR:-~/.config/zsh}/zsh_functions
source ${ZDOTDIR:-~/.config/zsh}/zsh_aliases # zsh_functions needed.

# oh-my-zsh options
export ZSH="${HOME}/.config/zsh/oh-my-zsh"
export ZSH_CUSTOM="${ZDOTDIR}/omz-customizations"
DEFAULT_USER="waltripc"
ZSH_THEME="agnoster"
CASE_SENSITIVE="true" # Case-sensitive completion
# HYPHEN_INSENSITIVE="true" # Hyphen-insensitive - Case-sensitive must be off.
# DISABLE_AUTO_UPDATE="true"
DISABLE_UPDATE_PROMPT="true" # Update without prompting
# export UPDATE_ZSH_DAYS=13 # Interval to check for updates
# DISABLE_MAGIC_FUNCTIONS="true" # Fix pasting URLS/other text.
# DISABLE_AUTO_TITLE="true" 
COMPLETION_WAITING_DOTS="true" # Add red dots whilst waiting for completion.
#DISABLE_UNTRACKED_FILES_DIRTY="true" # Speed up prompt @ large VCS repos
# ZSH_CUSTOM=/path/to/new-custom-folder # Custom zsh plugins directory
VSCODE=code
ZSH_DISABLE_COMPFIX="true"

# oh-my-zsh plugins
plugins=(git gitfast aws battery brew colored-man-pages colorize)
plugins+=(command-not-found)
plugins+=(emoji iterm2 osx tmux vscode)

# Start oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Is git-extras installed?
which git-extras &>> /dev/null
if ((! PIPESTATUS)); then
    if is_macos; then
        f="/usr/local/opt/git-extras/share/git-extras/git-extras-completion.zsh"
        if [[ ! -f ${f} ]]; then
            f="$(brew list git-extras | grep "git-extras-completion\.zsh$")"
        fi
        git_ex_comp_file="${f}"
    elif is_redhat_based; then
        # NOTE (Chris): git-extras RPM doesn't install ZSH completions and so
        #               this needs to be installed from source or a new SPEC
        #               file needs to be made.
        # TODO (Chris): Create new rpm spec file for this that includes zsh.
        unset git_ex_comp_file
        #git_ex_comp_file=$()
    elif is_debian_based; then
        f=$(dpkg -L git-extras | grep "vendor-completions/_git-extras$")
        git_ex_comp_file="${f}"
    elif is_windows_based; then
        # TODO: Figure out where this is installed.
        unset git_ex_comp_file
    else
        unset git_ex_comp_file
    fi

    [[ -f "${git_ex_comp_file}" ]] && source "${git_ex_comp_file}"
fi

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
    export EDITOR=vim
else
    which -s code &>> /dev/null
    ((! PIPESTATUS)) && export EDITOR=code || export EDITOR=vim
fi

# Vim variables
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'

# Set the path
path_dirs=(
    ${HOME}/bin
    ${HOME}/.toolbox/bin
    /usr/local/aws/bin
)
for dir in ${path_dirs[@]}; do
    [[ -d ${dir} ]] && PATH="${dir}:${PATH}"
done
export PATH