#!/usr/bin/env zsh

if [[ -f /etc/os-release ]]; then
    local os=$(grep -m1 '^ID_LIKE=' /etc/os-release | awk -F= '{ print $2 }')
    if [[ "${os}" =~ "debian" ]]; then
        return 0
    fi
fi
return 1